---
resources:
- name: attendee-service
  type: git
  source:
    uri: https://github.com/vvrangan/pcf-attendee-service-code   #<----- REPLACE ME
    branch: concourse_deployment

- name: deploy-attendee-service
  type: cf
  source:
    api: api.run.pivotal.io        #<----- REPLACE ME
    username: ranganaathan.vv@cognizant.com
    password: Giridhar19$
    organization: Pivotal-Education-Students    #<----- REPLACE ME
    space: vvrangan-sandbox         #<----- REPLACE ME
    skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: attendee-service
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

